# cloudbuild.yaml
steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    id: 'Install Dependencies'
    args: ['ci']
    
  # Optimize build - gunakan --production flag
  - name: 'node:20'
    entrypoint: npm
    id: 'Build React App'
    args: ['run', 'build']
    env:
      - 'GENERATE_SOURCEMAP=false'
      - 'NODE_ENV=production'
      
  # Deploy ke App Engine dengan konfigurasi hemat
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    id: 'Deploy to App Engine'
    args:
      - '-c'
      - |
        gcloud app deploy --version=${SHORT_SHA} --quiet --no-promote

  # Langkah terpisah untuk membersihkan versi lama
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    id: 'Clean Old Versions'
    args:
      - '-c'
      - |
        # Simpan daftar semua versi, urutkan berdasarkan deployment terbaru
        VERSIONS=$(gcloud app versions list --service=asisten-tcc-5-fe --sort-by=~LAST_DEPLOYED --format="value(id)")
        
        # Ambil 2 baris pertama (2 versi terbaru) dan simpan
        KEEP_VERSIONS=$(echo "$VERSIONS" | head -n 2)
        
        # Ambil versi sisanya yang akan dihapus
        DELETE_VERSIONS=$(echo "$VERSIONS" | tail -n +3)
        
        # Hapus versi lama jika ada
        if [ -n "$DELETE_VERSIONS" ]; then
          echo "Deleting old versions: $DELETE_VERSIONS"
          gcloud app versions delete $DELETE_VERSIONS --quiet || echo "No old versions to delete"
        else
          echo "No old versions to delete"
        fi

# Gunakan builder dengan spesifikasi rendah
options:
  machineType: 'E2_MEDIUM'  # Machine type yang lebih kecil
  logging: CLOUD_LOGGING_ONLY
  
# Batasi timeout untuk memastikan tidak ada build yang terhenti terlalu lama
timeout: '600s'  # 10 menit
